package test;

import junit.framework.TestCase;
import project3.AdaptiveMST;

/**
 * The class <code>AdaptiveMSTTest</code> contains tests for the class {@link
 * <code>AdaptiveMST</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 12/6/14 7:23 PM
 *
 * @author Donald
 *
 * @version $Revision$
 */
public class AdaptiveMSTTest extends TestCase {

}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = test
 * package.sourceFolder = project3/src
 * superclassType = junit.framework.TestCase
 * testCase = AdaptiveMSTTest
 * testClassType = project3.AdaptiveMST
 */