

import static org.junit.Assert.assertArrayEquals;
import junit.framework.TestCase;

/**
 * The class <code>TraversalConverterTest</code> contains tests for the class
 * {@link <code>TraversalConverter</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 11/23/14 7:48 PM
 *
 * @author Donald
 *
 * @version $Revision$
 */
public class TraversalConverterTest extends TestCase {
	
	/**
	 * Run the String[] search_pre_to_post(String[]) method test
	 */
	public void testSearch_pre_to_post() {
		String[] pre = {"20","10","6","15","30","35"};
		String[] post = {"6","15","10","35","30","20"};
		String[] test = TraversalConverter.search_pre_to_post(pre);
		
		for (String s : test){
			System.out.println(s);
		}
		assertArrayEquals(post, test);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = pre_in_to_post([QString;![QString;),pre_post_to_in([QString;![QString;),pre_to_post_recurse([I!I),search_pre_to_post([QString;)
 * package = 
 * package.sourceFolder = project2/tests
 * superclassType = junit.framework.TestCase
 * testCase = TraversalConverterTest
 * testClassType = TraversalConverter
 */